### ISSUE TITLE
Maybe add example of how to use directly on route?

### ISSUE THREAD

**Issue by emmanuelay** [tpkeeper/gin-dump#3]
Hi! Nice work!

Would be nice if the Dump() method did not require "nil" to perform standard (stdout) and if you could add examples to the README showing how to use the middleware in both groups and endpoints aswell:

Group
```
router := gin.New()
dumpAll := router.Group("/group")
dumpAll.Use(gindump.Dump(nil))
dumpAll.POST("/", MyEndpointHandler)
dumpAll.PUT("/", MyOtherEndpointHandler)
```

Endpoint
```
router := gin.New()
dumpOne := router.Group("/group")
dumpOne.POST("/", gindump.Dump(nil), MyEndpointHandler)
```

**Comment by tpkeeper** [comment]
thanks very much
that's cool !
